export const ADD_ORDER = 'ADD_ORDER';

export const FETCH_ORDER_PENDING = "FETCH_ORDER_PENDING"
export const FETCH_ORDER_SHIPPING = "FETCH_ORDER_SHIPPING" 
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS"
export const FETCH_ORDER_CANCEL = "FETCH_ORDER_CANCEL"

export const UPDATE_STATUS = "UPDATE_STATUS"