export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

export const FETCH_DETAIL_PRODUCTS = 'FETCH_DETAIL_PRODUCTS';

export const FETCH_PRODUCTS_BY_BRAND = 'FETCH_PRODUCTS_BY_BRAND';

export const FETCH_LINE_PRODUCTS_NEW = 'FETCH_LINE_PRODUCTS_NEW';